### ISSUE TITLE
Cannot identify the Xtensa binary

### ISSUE THREAD

**Issue by BBge** [airbus-seclab/cpu_rec#7] opened 2019-06-25 15:58 UTC
I have one binary which architecture is Xtensa.
But the cpu_rec cannot recognize it.

The binary download link: https://drive.google.com/open?id=11mcHfEOCD8KkCEz0-iIPrvMqJt5ApuLb

**Comment by LRGH** [comment] 2019-06-25 18:49
Thank you for providing this file.
With the current version of cpu_rec I can recognise it as Xtensa.
```
% python2.7 cpu_rec.py esp_warm_light_qpd_target_2.3.0.bin
esp_warm_light_qpd_target_2.3.0.bin          full(0xff000)  None       chunk(0x2c000;88)   Xtensa
% binwalk -% esp_warm_light_qpd_target_2.3.0.bin
DECIMAL       HEXADECIMAL     DESCRIPTION
--------------------------------------------------------------------------------
0             0x0             None (size=0x1000, entropy=0.642949)
4096          0x1000          Xtensa (size=0x6000, entropy=0.834623)
28672         0x7000          None (size=0x800, entropy=0.758923)
30720         0x7800          Xtensa (size=0x11800, entropy=0.858477)
102400        0x19000         None (size=0x800, entropy=0.793911)
104448        0x19800         Xtensa (size=0x10000, entropy=0.890330)
169984        0x29800         STM8 (size=0x3000, entropy=0.645237)
182272        0x2C800         None (size=0x3000, entropy=0.757618)
194560        0x2F800         Xtensa (size=0x2c000, entropy=0.876653)
374784        0x5B800         None (size=0xa3800, entropy=0.032267)
```
What was your output?

**Comment by LRGH** [comment] 2019-07-19 05:57
Closing the issue, because I did not reproduce it.

**Closed as completed** 2019-07-19 05:57 UTC
